ALTER TABLE users
ADD COLUMN password VARCHAR(60) NOT NULL DEFAULT '',
ADD COLUMN salt VARCHAR(29) NOT NULL DEFAULT '',
ADD COLUMN active BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN last_login TIMESTAMP,
ADD COLUMN reset_token VARCHAR(36),
ADD COLUMN reset_token_expiry TIMESTAMP; 